version: '3.8'

networks:
  alphabethbr-aries-mysql-network:
    driver: bridge

services:
  alphabethbr-aries-mysql:
    image: mysql:5.7.17
    container_name: alphabethbr-aries-mysql
    hostname: alphabethbr-aries-mysql
    networks:
      - alphabethbr-aries-mysql-network
    volumes:
      - ./.docker/alphabethbr-aries-mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aries
      - TZ=America/Sao_Paulo
    restart: always